### ISSUE TITLE
Automatically add configs to further reduce the vmlinux size

### ISSUE THREAD

**Issue by lastweek** [hckuo/Cozart#16]
This is a very interesting and useful work! Great hacks! After reading the paper, I couldn't resist the idea of automatically adding more CONFIGs to the kernel source to further rule out unused built-in code, e.g., unused syscalls. In other words, only the used kernel code is compiled, all others are ruled out, this could further reduce attack surface and this kernel can even be used as the basis for libos. Have you guys looked into this particular direction?

**Comment by tianyin** [comment]
@lastweek sorry I don't think I understand what you're proposing :( 

What do you mean by "adding more configs into the kernel source"?
Can you give a concrete example? 

From a very high level, we are indeed manipulating the "configs" to only compile the used code.

**Comment by lastweek** [comment]
Hi @tianyin thank you for the reply!

There are a lot built-in kernel code that is not covered/controlled by any config options. For instance, the syscall [sched_setattr](https://github.com/torvalds/linux/blob/master/kernel/sched/core.c#L5199) is always present in a x86 kernel, there is no way to disable it even if it's not invoked.

If we want to tailor the kernel for the app to an extreme, the above kind of code should be omitted. This is not a drawback of the Cozart tool itself, but rather the kernel source code itself lacks of a finer-grained option (above case, maybe a CONFIG_HAVE_SCHED_SETATTR).

I was saying that cozard could probably further reduce the image size by avoiding compiling above code, maybe by generate and insert new configs to kernel source code.  (Since Cozart is using QEMU+addr2line to profile the code coverage, it's able to know which portion of the kernel is used, which is not.)

This maybe not necessary given the cozard tailored kernel is already very small, i was just curious

**Comment by tianyin** [comment]
This is an interesting idea! I like it!

One challenge is to understand the dependencies between the configs (currently it's manually tracked by kconfig) if we want to do it in an automatic way.

@hckuo

**Comment by hckuo** [comment]
Hi @lastweek,

I actually thought about this idea before. The first challenge would be find functions that are uniquely called by a certain system call. Adding config options for system calls would need to slice the kernel into multiple disjoint pieces so that you can disable a certain piece and get the benefit of debloating. I am not sure if it is even feasible. For example, not only syscall `open()` calls `do_open` but some other kernel routines call it such as the boot routine. To sum up, I think that add config options for system calls is difficult but we can combine cozart if we are able to rule out such options.

**Comment by tianyin** [comment]
> For example, not only syscall open() calls do_open but some other kernel routines call it such as the boot routine

This does not sound too difficult -- if you are able to get a call graph, it's trivial.

**Comment by hckuo** [comment]
It is not difficult to find a call graph. But my experience was that it is difficult to slice the kernel into pieces by just looking at the call graph because these functions are connected together. The result is likely to be config options that only remove the entry of a system call which does not reduce the size of vmlinux. But you can argue that it make the entry of the kernel smaller.

**Comment by lastweek** [comment]
Hi @hckuo and @tianyin,

> add config options for system calls is difficult
maybe some other built-in stuff other than syscalls, sth like irq_desc tables, IRQ handlers, swap-subsystem (if guaranteed to never happen :)) if we want to go all the way down..

> This does not sound too difficult -- if you are able to get a call graph, it's trivial.
exactly, if we could get the call graph, which I believe cozart already can, we should be able to get a precise list of used functions and unused ones (the ones outside config area).

**Comment by hckuo** [comment]
for swap: https://cateee.net/lkddb/web-lkddb/SWAP.html

**Comment by lastweek** [comment]
in your testing, is CONFIG_SWAP is always on or sometimes being turned off? My guess is that these essential subsystems are by default on. However, like swap-subsystem, it's something that can be avoided if certain trigger events (oom/cgroup) are ruled out. This kind config relies on runtime behavior, cozart seems cannot catch

**Comment by hckuo** [comment]
CONFIG_SWAP one of the rare options that are defaulted to YES. Cozart does not use any of the runtime information but I agree that we can have a better config if we can leverage runtime info.

**Comment by lastweek** [comment]
Good to know. Thank you guys, very fruitful discussion.

**Comment by tianyin** [comment]
> This kind config relies on runtime behavior, cozart seems cannot catch

Cozart actually deals with runtime behavior, e.g., if it observes the use of huge pages in a workload, it will include THP related modules. 

On the other hand, the key limitation of Cozart (and many other kernel debloating methods) is that it really relies on the completeness/fidelity of tests/workloads which may not be the case in reality. Unfortunately, recompiling the kernel is not as fast as updating a seccomp filter.

**Comment by lastweek** [comment]
> if it observes the use of huge pages in a workload, it will include THP related module

That's cool!

> the key limitation of Cozart (and many other kernel debloating methods) is that it really relies on the completeness/fidelity of tests/workloads which may not be the case in reality

btw, for a certain build, do you guys get the code coverage of the application binary as well? i.e., 80% of the app has been tested. In rare cases, the remaining 20% code may need some extra kernel syscalls/services. It feels a fuzzy+cozart solution can have a higher confidence on the completeness.

**Comment by tianyin** [comment]
@lastweek yes, we use `gcov` to get the coverage of app binaries (discussed in 7.4). 

Fuzzing indeed can significantly improve the coverage for sure. We discussed it in S7.4. 

In my personal opinion, the current fuzzing techniques are still limited, especially for big applications such as a web server or a database server. The current fuzzing has problems to go deeper. But for small applications such as functions in serverless settings, it is feasible. 

The real hard part is that even with a 100% code coverage (which means that all the syscalls can be covered), it may not be sufficient -- only syscall IDs are covered doesn't mean all the arguments can be covered and different arguments lead to different kernel reach.

**Comment by jo285317** [comment]
> It is not difficult to find a call graph. But my experience was that it is difficult to slice the kernel into pieces by just looking at the call graph because these functions are connected together. The result is likely to be config options that only remove the entry of a system call which does not reduce the size of vmlinux. But you can argue that it make the entry of the kernel smaller.

How have you generated call graphs, and have you been able to account for function pointers? I have found some success with building with clang and using llvm tools to generate kernel call graphs -- but they don't include function pointers.

**Comment by tianyin** [comment]
@jo285317 I don't think we have done this and be able to account for function pointers :| 

// pointers are indeed a big problem

Does LLVM provide some analysis for function pointers?
